#!/usr/bin/env python3

# drawing_doc.py: the page of drawing functions, utils/harness/DRAWING.md,
# with one example per function and what it prints.
#
#   make drawing-doc           # regenerates it (make readme runs this too)
#
# Every output block is the real output of its example: the script runs each
# one under the venv, where sitecustomize has already loaded, and captures
# what it prints with the colours removed. Nothing is drawn by hand, so a
# change to a draw function shows up here on the next run.

import builtins
import io
import os
import re
import sys
import textwrap
from contextlib import redirect_stdout

from rich.console import Console

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
HARNESS = os.path.join(ROOT, "utils", "harness")
OUT = os.path.join(HARNESS, "DRAWING.md")

# (title, one-line explanation, example code)
EXAMPLES = [
    (
        "print(grid)",
        "`print` draws what it recognises: a list of lists is a table.",
        """
        dp = [[0, 1, 1, 1], [1, 2, 3, 4], [1, 3, 6, 10]]
        print(dp)
        """,
    ),
    (
        "tabulate(rows, headers=(), row_labels=())",
        "A table with your own labels. Each distinct number gets its own colour.",
        """
        tabulate([[0, 1, 2], [1, 1, 2]], headers=list("abc"), row_labels=["x", "y"])
        """,
    ),
    (
        "draw_tree(root)",
        "A binary tree. `print(root)` does the same for a `TreeNode`.",
        """
        root = build_tree([4, 2, 7, 1, 3, 6, 9])
        draw_tree(root)
        """,
    ),
    (
        "draw_linked_list(head)",
        "A linked list. `print(head)` does the same for a `ListNode`.",
        """
        head = ListNode(1, ListNode(2, ListNode(3)))
        draw_linked_list(head)
        """,
    ),
    (
        "draw_general_tree(root)",
        "A tree whose nodes have any number of children (N-ary).",
        """
        root = build_nary_tree([1, None, 3, 2, 4, None, 5, 6])
        draw_general_tree(root)
        """,
    ),
    (
        "draw_ascii_graph(adj)",
        "A graph from a dict of lists or a dict of dicts. `print(adj)` does the same.",
        """
        adj = {0: [1, 2], 1: [3], 2: [3], 3: []}
        draw_ascii_graph(adj)
        """,
    ),
    (
        "draw_graph(adj)",
        "The same graph as an adjacency matrix.",
        """
        adj = {0: [1, 2], 1: [3], 2: [3], 3: []}
        draw_graph(adj)
        """,
    ),
    (
        "draw_heap(heap)",
        "A heap stored as a list, drawn as the tree it represents.",
        """
        heap = [1, 3, 2, 7, 4]
        draw_heap(heap)
        """,
    ),
    (
        "@viz_binary_search",
        "Traces a binary search: one bar per step, with mid marked by ok(mid).",
        """
        @viz_binary_search(width=60)
        def firstTrue(lo, hi, ok):
            while lo < hi:
                mid = (lo + hi) // 2
                if ok(mid):
                    hi = mid
                else:
                    lo = mid + 1
            return lo

        firstTrue(0, 20, lambda x: x * x >= 50)
        """,
    ),
]

BLANKS = re.compile(r"\A(\s*\n)+|(\n\s*)+\Z")
ANSI = re.compile(r"\x1b\[[0-9;]*m")


def run(code):
    """What code prints, without colours."""
    import sitecustomize

    buf = io.StringIO()
    old = sitecustomize.console
    sitecustomize.console = Console(
        file=buf, color_system=None, width=100
    )
    try:
        with redirect_stdout(buf):
            exec(code, {"__builtins__": builtins})
    finally:
        sitecustomize.console = old
    text = ANSI.sub("", buf.getvalue())
    return BLANKS.sub("", "\n".join(ln.rstrip() for ln in text.split("\n")))


def main():
    out = [
        "# Drawing functions",
        "",
        "Generated by `make drawing-doc` from utils/readme/drawing_doc.py.",
        "Each output block is what the code above it prints.",
        "",
    ]
    for title, line, code in EXAMPLES:
        code = textwrap.dedent(code).strip("\n") + "\n"
        out += [f"## `{title}`", "", line, "", "```python", code.rstrip("\n"), "```"]
        out += ["", "```text", run(code), "```", ""]
    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
