#!/usr/bin/env python3

# harness_doc.py: the reference for the helpers utils/harness/sitecustomize.py
# preloads into builtins, written to utils/harness/README.md.
#
#   make harness-doc           # regenerates it (make readme runs this too)
#
# The doc is read off the running harness, never hand-written: the script
# runs under the venv, where sitecustomize has already loaded, walks the
# `builtins.x = y` lines of sitecustomize.py in order under their `# section`
# comments, and keeps the names whose object is defined in the repo
# (utils/harness or dsa).
# Stdlib names the harness mirrors (deque, heappush, ...) are left out; they
# are documented by Python. Each kept name gets its signature and docstring.

import ast
import builtins
import inspect
import os
import re
import sys
import textwrap

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
HARNESS = os.path.join(ROOT, "utils", "harness")
OURS = (HARNESS, os.path.join(ROOT, "dsa"))
SITECUSTOMIZE = os.path.join(HARNESS, "sitecustomize.py")
OUT = os.path.join(HARNESS, "README.md")

SECTION = re.compile(r"^# ([a-z][a-z ]*)$")
ASSIGN = re.compile(r"^builtins\.(\w+)\s*=")


def sections(src):
    """(section title, [names]) pairs in source order; only the `# word` lines
    right before `builtins.` assignments count as titles."""
    out: list[tuple[str, list[str]]] = []
    title = None
    for line in src.splitlines():
        m = SECTION.match(line)
        if m:
            title = m.group(1)
            continue
        m = ASSIGN.match(line)
        if m and title:
            if not out or out[-1][0] != title:
                out.append((title, []))
            out[-1][1].append(m.group(1))
    return out


def is_ours(obj):
    """True if obj is defined under utils/harness or dsa (or in the venv's
    copy of sitecustomize, which is where the running one was loaded from)."""
    if getattr(obj, "__module__", None) == "sitecustomize":
        return True
    try:
        path = inspect.getsourcefile(obj)
    except TypeError:
        return False
    return path is not None and os.path.abspath(path).startswith(OURS)


def signature(name, obj):
    """The def line as written in the source, so defaults read as CARDINALS
    rather than the tuple they evaluate to. Classes show their __init__."""
    if inspect.isclass(obj):
        obj = obj.__init__
        prefix = f"class {name}"
    else:
        prefix = name
    try:
        node = ast.parse(textwrap.dedent(inspect.getsource(obj))).body[0]
    except (OSError, TypeError, SyntaxError):
        return prefix
    if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        return prefix
    if inspect.isclass(getattr(builtins, name, None)) and node.args.args:
        node.args.args = node.args.args[1:]
    params = ast.unparse(node.args).replace("=", " = ")
    ret = (
        f" -> {ast.unparse(node.returns)}"
        if node.returns and not prefix.startswith("class")
        else ""
    )
    return f"{prefix}({params}){ret}"


def entry(name):
    obj = getattr(builtins, name, None)
    if obj is None:
        return None
    if inspect.isroutine(obj) or inspect.isclass(obj):
        if not is_ours(obj):
            return None
        doc = inspect.getdoc(obj) or ""
        return (
            f"### `{signature(name, obj)}`\n\n{doc}\n"
            if doc
            else f"### `{signature(name, obj)}`\n"
        )
    if isinstance(obj, tuple) and all(isinstance(x, tuple) for x in obj):
        return f"### `{name}`\n\n`{obj!r}`\n"
    return None


def render(src):
    lines = [
        "# Harness helpers",
        "",
        "Generated by `make harness-doc` from `utils/harness/sitecustomize.py`;",
        "do not edit by hand. These names are preloaded into builtins for every",
        "solve run in the repo venv, alongside the stdlib names LeetCode",
        "preloads (`deque`, `heappush`, `Counter`, ...), which are not listed.",
        "Set `PRETTY_PRINT=1` and `print` becomes `pprint`.",
        "",
    ]
    for title, names in sections(src):
        entries = [e for e in (entry(n) for n in names) if e]
        if not entries:
            continue
        lines += [f"## {title}", ""]
        lines += entries
    return "\n".join(lines).rstrip() + "\n"


def main():
    if not hasattr(builtins, "nbrs"):
        sys.exit("run under the repo venv: sitecustomize did not load")
    with open(SITECUSTOMIZE) as f:
        src = f.read()
    with open(OUT, "w") as f:
        f.write(render(src))
    print(f"wrote {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
