# Type stubs for kg_rs, the Rust extension built from utils/rs/kg_py.
# Keep in step with src/lib.rs next to it; pyproject.toml puts this directory on mypy_path.

def drill_key(fname: str) -> str | None: ...
def degree_color(degree: float) -> str: ...
