[package]
name = "kg_next"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kg_next"
path = "src/main.rs"

[dependencies]
kg_mock = { path = "../kg_mock_rs" }
libc = "0.2"
serde_json = { version = "1", features = ["preserve_order"] }
indexmap = "2"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }

[profile.release]
lto = true
