from typing import (
    List as List,
    Optional as Optional,
    Dict as Dict,
    Tuple as Tuple,
    Any as Any,
    Callable as Callable,
    Generic as Generic,
    Iterable as Iterable,
    Iterator as Iterator,
    TypeVar as TypeVar,
    Union as Union,
    overload as overload,
)

# Custom classes
class TreeNode:
    val: int
    left: Optional['TreeNode']
    right: Optional['TreeNode']
    def __init__(self, val: int = 0, left: Optional['TreeNode'] = None, right: Optional['TreeNode'] = None) -> None: ...

class ListNode:
    val: int
    next: Optional['ListNode']
    def __init__(self, val: int = 0, next: Optional['ListNode'] = None) -> None: ...
    def __repr__(self) -> str: ...

class Node:
    val: Any
    children: Dict[Any, 'Node']
    def __init__(self, val: Any, children: Dict[Any, 'Node'] = ...) -> None: ...

# Class stubs
class Counter(Dict[Any, int]):
    def __init__(self, iterable: Optional[Iterable[Any]] = None, **kwds: int) -> None: ...

class defaultdict(Dict[Any, Any]):
    def __init__(self, default_factory: Optional[Callable[[], Any]] = None, *args: Any, **kwargs: Any) -> None: ...

dd = defaultdict

# Function stubs for shortcuts
def groupby(iterable: Iterable[Any], key: Optional[Callable[[Any], Any]] = None) -> Iterator[Tuple[Any, Iterator[Any]]]: ...

def combinations(iterable: Iterable[Any], r: int) -> Iterator[Tuple[Any, ...]]: ...

def log10(x: float) -> float: ...

def log2(x: float) -> float: ...

def floor(x: float) -> int: ...

def ceil(x: float) -> int: ...

def pairwise(iterable: Iterable[Any]) -> Iterator[Tuple[Any, Any]]: ...

def zip_longest(*iterables: Iterable[Any], fillvalue: Any = None) -> Iterator[Tuple[Any, ...]]: ...

def reduce(function: Callable[..., Any], iterable: Iterable[Any], initializer: Any = ...) -> Any: ...

def takewhile(predicate: Callable[[Any], bool], iterable: Iterable[Any]) -> Iterator[Any]: ...

def prod(iterable: Iterable[int], *, start: int = 1) -> int: ...

def product(*iterables: Iterable[Any], repeat: int = 1) -> Iterator[Tuple[Any, ...]]: ...

def enumerate(iterable: Iterable[Any], start: int = 0) -> Iterator[Tuple[int, Any]]: ...

enumr = enumerate

def accumulate(iterable: Iterable[Any], func: Optional[Callable[[Any, Any], Any]] = None, *, initial: Any = None) -> Iterator[Any]: ...

def bisect_left(a: List[Any], x: Any, lo: int = 0, hi: int = ...) -> int: ...

def bisect_right(a: List[Any], x: Any, lo: int = 0, hi: int = ...) -> int: ...

def chain(*iterables: Iterable[Any]) -> Iterator[Any]: ...

def add(a: Any, b: Any) -> Any: ...

def xor(a: Any, b: Any) -> Any: ...

def heapify(heap: List[Any]) -> None: ...

def heappop(heap: List[Any]) -> Any: ...

def heappush(heap: List[Any], item: Any) -> None: ...

def nlargest(n: int, iterable: Iterable[Any], key: Optional[Callable[[Any], Any]] = None) -> List[Any]: ...

def nsmallest(n: int, iterable: Iterable[Any], key: Optional[Callable[[Any], Any]] = None) -> List[Any]: ...

ascii_letters: str

ascii_lowercase: str

ascii_uppercase: str

def match(pattern: str, string: str, flags: int = 0) -> Any: ...

def permutations(iterable: Iterable[Any], r: Optional[int] = None) -> Iterator[Tuple[Any, ...]]: ...

def or_(a: Any, b: Any) -> Any: ...

def and_(a: Any, b: Any) -> Any: ...

# Pretty printing
def tabulate(*args: Any, **kwargs: Any) -> str: ...

def rich_print(*args: Any, **kwargs: Any) -> None: ...

# Utils from tree_utils, bst_utils, linked_list_utils
def draw_tree(root: Optional[TreeNode]) -> None: ...

def draw_linked_list(head: Optional[ListNode]) -> None: ...

def draw_general_tree(root: Optional[Node]) -> None: ...

def get_level_order(root: Optional[TreeNode]) -> List[Optional[int]]: ...

def build_tree(arr: List[Optional[int]]) -> Optional[TreeNode]: ...

def generate_and_print_random_bst(n: int, seed: Optional[int] = None, verbose: bool = True) -> Optional[TreeNode]: ...

def generate_full_binary_tree(height: int) -> Optional[TreeNode]: ...

def get_list_values(head: Optional[ListNode]) -> List[int]: ...

def print_linked_list(head: Optional[ListNode]) -> None: ...

def build_linked_list(vals: List[int]) -> Optional[ListNode]: ...

def find_node(root: Optional[TreeNode], val: int) -> Optional[TreeNode]: ...

def get_inorder(root: Optional[TreeNode]) -> List[int]: ...

def is_balanced(root: Optional[TreeNode]) -> bool: ...

def is_valid_bst(root: Optional[TreeNode]) -> bool: ...