from __future__ import annotations

from typing import (
    List as List,
    Optional as Optional,
    Dict as Dict,
    Tuple as Tuple,
    Any as Any,
    Callable as Callable,
    Generic as Generic,
    Iterable as Iterable,
    Iterator as Iterator,
    TypeVar as TypeVar,
    Union as Union,
    overload as overload,
)

# Custom classes
class TreeNode:
    val: int
    left: Optional[TreeNode]
    right: Optional[TreeNode]
    def __init__(
        self,
        val: int = 0,
        left: Optional[TreeNode] = None,
        right: Optional[TreeNode] = None,
    ) -> None: ...

class ListNode:
    val: int
    next: Optional[ListNode]
    def __init__(self, val: int = 0, next: Optional[ListNode] = None) -> None: ...
    def __repr__(self) -> str: ...

class Node:
    val: Any
    children: Dict[Any, Node]
    def __init__(self, val: Any, children: Dict[Any, Node] = ...) -> None: ...

# Classes from collections
_T = TypeVar("_T")
_KT = TypeVar("_KT")
_VT = TypeVar("_VT")

class Counter(Dict[_KT, int]):
    def __init__(self, iterable: Iterable[_KT] = ..., **kwds: int) -> None: ...

class defaultdict(Dict[_KT, _VT]):
    def __init__(
        self,
        default_factory: Optional[Callable[[], _VT]] = None,
        /,
        *args: Any,
        **kwargs: Any,
    ) -> None: ...

dd = defaultdict

# Function stubs for shortcuts
def log10(__x: float) -> float: ...
def log2(__x: float) -> float: ...
def floor(__x: float) -> int: ...
def ceil(__x: float) -> int: ...
def prod(__iterable: Iterable[int], *, start: int = 1) -> int: ...
def groupby(
    iterable: Iterable[_T], key: Optional[Callable[[_T], _KT]] = None
) -> Iterator[Tuple[_KT, Iterator[_T]]]: ...
def combinations(iterable: Iterable[_T], r: int) -> Iterator[Tuple[_T, ...]]: ...
def pairwise(iterable: Iterable[_T]) -> Iterator[Tuple[_T, _T]]: ...
def zip_longest(
    *iterables: Iterable[_T], fillvalue: Any = None
) -> Iterator[Tuple[Any, ...]]: ...
def reduce(
    function: Callable[..., _T],
    iterable: Iterable[_T],
    initializer: Optional[_T] = None,
) -> _T: ...
def takewhile(
    predicate: Callable[[_T], object], iterable: Iterable[_T]
) -> Iterator[_T]: ...
def product(*iterables: Iterable[_T], repeat: int = 1) -> Iterator[Tuple[_T, ...]]: ...
def accumulate(
    iterable: Iterable[_T],
    func: Optional[Callable[[_T, _T], _T]] = None,
    *,
    initial: Optional[_T] = None,
) -> Iterator[_T]: ...
def chain(*iterables: Iterable[_T]) -> Iterator[_T]: ...
def permutations(
    iterable: Iterable[_T], r: Optional[int] = None
) -> Iterator[Tuple[_T, ...]]: ...
def bisect_left(a: List[_T], x: _T, lo: int = 0, hi: Optional[int] = None) -> int: ...
def bisect_right(a: List[_T], x: _T, lo: int = 0, hi: Optional[int] = None) -> int: ...
def add(__a: Any, __b: Any) -> Any: ...
def xor(__a: Any, __b: Any) -> Any: ...
def or_(__a: Any, __b: Any) -> Any: ...
def and_(__a: Any, __b: Any) -> Any: ...
def heapify(__heap: List[_T]) -> None: ...
def heappop(__heap: List[_T]) -> _T: ...
def heappush(__heap: List[_T], __item: _T) -> None: ...
def nlargest(
    __n: int, __iterable: Iterable[_T], __key: Optional[Callable[[_T], Any]] = None
) -> List[_T]: ...
def nsmallest(
    __n: int, __iterable: Iterable[_T], __key: Optional[Callable[[_T], Any]] = None
) -> List[_T]: ...

ascii_letters: str
ascii_lowercase: str
ascii_uppercase: str

def match(pattern: str, string: str, flags: int = 0) -> Optional[Any]: ...
def enumr(iterable: Iterable[_T], start: int = 0) -> Iterator[Tuple[int, _T]]: ...

# Pretty printing
def tabulate(
    tabular_data: Iterable[Iterable[Any]], headers: Iterable[str] = ..., **kwargs: Any
) -> str: ...
def rich_print(*args: Any, **kwargs: Any) -> None: ...

# Utils from tree_utils, bst_utils, linked_list_utils
def draw_tree(root: Optional[TreeNode]) -> None: ...
def draw_linked_list(head: Optional[ListNode]) -> None: ...
def draw_general_tree(root: Optional[Node]) -> None: ...
def get_level_order(root: Optional[TreeNode]) -> List[Optional[int]]: ...
def viz_binary_search(*args: Any, **kwargs: Any) -> Any: ...
def build_tree(arr: List[Optional[int]]) -> Optional[TreeNode]: ...
def generate_and_print_random_bst(
    n: int, seed: Optional[int] = None, verbose: bool = True
) -> Optional[TreeNode]: ...
def generate_full_binary_tree(height: int) -> Optional[TreeNode]: ...
def get_list_values(head: Optional[ListNode]) -> List[int]: ...
def print_linked_list(head: Optional[ListNode]) -> None: ...
def build_linked_list(vals: List[int]) -> Optional[ListNode]: ...
def find_node(root: Optional[TreeNode], val: Any) -> Optional[TreeNode]: ...
def get_inorder(root: Optional[TreeNode]) -> List[int]: ...
def is_balanced(root: Optional[TreeNode]) -> bool: ...
def is_valid_bst(root: Optional[TreeNode]) -> bool: ...
