from typing import (
    Any as Any,
    Dict as Dict,
    Generic as Generic,
    Iterable as Iterable,
    Iterator as Iterator,
    List as List,
    Optional as Optional,
    Tuple as Tuple,
    TypeVar as TypeVar,
    Union as Union,
    overload as overload,
)
from collections.abc import Callable as Callable
from collections import (
    Counter as _Counter,
    defaultdict as _defaultdict,
    deque as _deque,
)
import heapq
import operator
import re
from functools import reduce as _reduce
from itertools import (
    accumulate as _accumulate,
    chain as _chain,
    combinations as _combinations,
    compress as _compress,
    groupby as _groupby,
    islice as _islice,
    pairwise as _pairwise,
    permutations as _permutations,
    product as _product,
    starmap as _starmap,
    takewhile as _takewhile,
    zip_longest as _zip_longest,
)
from math import (
    ceil as _ceil,
    floor as _floor,
    log10 as _log10,
    log2 as _log2,
    prod as _prod,
    sqrt as _sqrt,
)
import sys
from typing import Sequence

T = TypeVar("T")
S = TypeVar("S")
K = TypeVar("K")

# Type aliases (already imported as aliases)

# Custom classes added to builtins
class TreeNode:
    def __init__(
        self,
        val: int = 0,
        left: Optional["TreeNode"] = None,
        right: Optional["TreeNode"] = None,
    ) -> None: ...
    val: int
    left: Optional["TreeNode"]
    right: Optional["TreeNode"]

class ListNode:
    def __init__(self, val: int = 0, next: Optional["ListNode"] = None) -> None: ...
    val: int
    next: Optional["ListNode"]
    def __repr__(self) -> str: ...

class GraphNode:
    def __init__(
        self, val: int = 0, neighbors: Optional[List["GraphNode"]] = None
    ) -> None: ...
    val: int
    neighbors: List["GraphNode"]
    def __repr__(self) -> str: ...

# Internal class for draw_general_tree
class Node:
    def __init__(self, val: Any, children: Dict[Any, "Node"] = ...) -> None: ...
    val: Any
    children: Dict[Any, "Node"]

# Class stubs for collections
class Counter(_Counter[T]): ...
class defaultdict(_defaultdict[T, S]): ...
class deque(_deque[T]): ...

# Constants
maxsize: int
ascii_letters: str
ascii_lowercase: str
ascii_uppercase: str

# Function stubs for math
def log10(x: float) -> float: ...
def log2(x: float) -> float: ...
def floor(x: float) -> int: ...
def ceil(x: float) -> int: ...
def prod(
    iterable: Iterable[Union[int, float]], *, start: Union[int, float] = 1
) -> Union[int, float]: ...
def sqrt(x: float) -> float: ...

# Function stubs for itertools
def groupby(
    iterable: Iterable[T], key: Optional[Callable[[T], S]] = None
) -> Iterator[Tuple[S, Iterator[T]]]: ...
def combinations(iterable: Iterable[T], r: int) -> Iterator[Tuple[T, ...]]: ...
def pairwise(iterable: Iterable[T]) -> Iterator[Tuple[T, T]]: ...
def zip_longest(
    *iterables: Iterable[Any], fillvalue: Any = None
) -> Iterator[Tuple[Any, ...]]: ...
def takewhile(predicate: Callable[[T], bool], iterable: Iterable[T]) -> Iterator[T]: ...
def product(*iterables: Iterable[T], repeat: int = 1) -> Iterator[Tuple[T, ...]]: ...
def accumulate(
    iterable: Iterable[T],
    func: Callable[[T, T], T] = ...,
    *,
    initial: Optional[T] = None
) -> Iterator[T]: ...
def chain(*iterables: Iterable[T]) -> Iterator[T]: ...
def permutations(
    iterable: Iterable[T], r: Optional[int] = None
) -> Iterator[Tuple[T, ...]]: ...
def islice(
    iterable: Iterable[T],
    start: Optional[int],
    stop: Optional[int] = None,
    step: int = 1,
) -> Iterator[T]: ...
def compress(data: Iterable[T], selectors: Iterable[Any]) -> Iterator[T]: ...
def starmap(
    function: Callable[..., S], iterable: Iterable[Iterable[Any]]
) -> Iterator[S]: ...

# Function stubs for functools
def reduce(
    function: Callable[[T, S], T], sequence: Iterable[S], initial: Optional[T] = ...
) -> T: ...

# Function stubs for operator
def add(a: T, b: T) -> T: ...
def iadd(a: T, b: T) -> T: ...
def sub(a: T, b: T) -> T: ...
def isub(a: T, b: T) -> T: ...
def xor(a: T, b: T) -> T: ...
def ixor(a: T, b: T) -> T: ...
def or_(a: T, b: T) -> T: ...
def ior(a: T, b: T) -> T: ...
def and_(a: T, b: T) -> T: ...

# Function stubs for heapq
def heapify(heap: List[T]) -> None: ...
def heappop(heap: List[T]) -> T: ...
def heappush(heap: List[T], item: T) -> None: ...
def nlargest(
    n: int, iterable: Iterable[T], key: Optional[Callable[[T], Any]] = None
) -> List[T]: ...
def nsmallest(
    n: int, iterable: Iterable[T], key: Optional[Callable[[T], Any]] = None
) -> List[T]: ...

# Function stubs for re
def match(pattern: str, string: str, flags: int = 0) -> Optional[re.Match]: ...

# Function stubs for bisect
def bisect_left(a: Sequence[T], x: T, lo: int = 0, hi: Optional[int] = None) -> int: ...
def bisect_right(
    a: Sequence[T], x: T, lo: int = 0, hi: Optional[int] = None
) -> int: ...

# Alias for enumerate
def enumr(iterable: Iterable[T], start: int = 0) -> Iterator[Tuple[int, T]]: ...

# Custom batched
def batched(s: Sequence[T], n: int = 1) -> List[Sequence[T]]: ...

# dd alias
dd: Callable[..., defaultdict[Any, Any]]

# Pretty printing stubs
def tabulate(*args: Any, **kwargs: Any) -> str: ...
def rich_print(*args: Any, **kwargs: Any) -> None: ...

# Stubs for tree_utils
def find_node(root: Optional[TreeNode], val: Any) -> Optional[TreeNode]: ...
def build_tree(arr: List[Optional[int]]) -> Optional[TreeNode]: ...
def draw_tree(root: Optional[TreeNode]) -> None: ...
def draw_general_tree(root: Optional[Node]) -> None: ...
def generate_full_binary_tree(height: int) -> Optional[TreeNode]: ...
def get_inorder(root: Optional[TreeNode]) -> List[int]: ...
def is_balanced(root: Optional[TreeNode]) -> bool: ...
def get_level_order(root: Optional[TreeNode]) -> List[Optional[int]]: ...

# Stubs for bst_utils
def insert(root: Optional[TreeNode], val: int) -> TreeNode: ...
def generate_random_bst(n: int, seed: Optional[int] = None) -> Optional[TreeNode]: ...
def tree_to_list(root: Optional[TreeNode]) -> List[Optional[int]]: ...
def is_valid_bst(root: Optional[TreeNode]) -> bool: ...
def generate_and_print_random_bst(
    n: int, seed: Optional[int] = None, verbose: bool = True
) -> Optional[TreeNode]: ...

# Stubs for linked_list_utils
def build_linked_list(vals: Iterable[int]) -> Optional[ListNode]: ...
def print_linked_list(head: Optional[ListNode]) -> None: ...
def get_list_values(head: Optional[ListNode]) -> List[int]: ...
def draw_linked_list(head: Optional[ListNode]) -> None: ...

# Stubs for other utils (not provided, using generic Any)
def debug_var(*args: Any, **kwargs: Any) -> Any: ...
def debug_vars(*args: Any, **kwargs: Any) -> Any: ...
def viz_binary_search(*args: Any, **kwargs: Any) -> Any: ...
def draw_ascii_graph(*args: Any, **kwargs: Any) -> Any: ...
def draw_graphviz(*args: Any, **kwargs: Any) -> Any: ...
def draw_graph(*args: Any, **kwargs: Any) -> Any: ...
def draw_heap(*args: Any, **kwargs: Any) -> Any: ...
def get_adj_list(*args: Any, **kwargs: Any) -> Any: ...
def build_graph(*args: Any, **kwargs: Any) -> Any: ...
