"""
URL: https://leetcode.com/problems/remove-palindromic-subsequences/description/?envType=problem-list-v2&envId=vn57k9wr

1332. Remove Palindromic Subsequences

You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string if it is generated by deleting some characters of a given string without changing its order. Note that a subsequence does not necessarily need to be contiguous.

A string is called palindrome if is one that reads the same backward as well as forward.

Example 1:

Input: s = "ababa"
Output: 1
Explanation: s is already a palindrome, so its entirety can be removed in a single step.

Example 2:

Input: s = "abb"
Output: 2
Explanation: "abb" -> "bb" -> "".
Remove palindromic subsequence "a" then "bb".

Example 3:

Input: s = "baabb"
Output: 2
Explanation: "baabb" -> "b" -> "".
Remove palindromic subsequence "baab" then "b".

Constraints:

    1 <= s.length <= 1000
    s[i] is either 'a' or 'b'.

---

This would be a difficult question were it not for a subsequence.

- if the string is empty, then the minimum number of steps to get an empty string is 0.
- if it's a palindrome, then return 1
- else return 2

The key insight is that if it's not a palindrome, we can remove a subsequence of as and a subsequence of bs.

Keys to solving the question:

- read the question carefully. Pay attention to each word and constraint:
    - the word 'subsequence' mattered a lot
    - the fact it's only as and bs was very important
    - think of the min and max possible output

"""


class Solution:

    def isPalindrome(self, s):
        return all(s[i] == s[~i] for i in range(len(s)))

    def removePalindromeSub(self, s: str) -> int:
        if not len(s):
            return 0
        elif self.isPalindrome(s):
            return 1
        else:
            return 2


sol = Solution()

# print(sol.removePalindromeSub("ababa"))  # 1

assert sol.removePalindromeSub("ababa") == 1
assert sol.removePalindromeSub("abb") == 2
assert sol.removePalindromeSub("baabb") == 2
assert sol.removePalindromeSub("") == 0
assert sol.removePalindromeSub("a") == 1
assert sol.removePalindromeSub("b") == 1
assert sol.removePalindromeSub("aa") == 1
assert sol.removePalindromeSub("bb") == 1
assert sol.removePalindromeSub("ab") == 2
assert sol.removePalindromeSub("ba") == 2
assert sol.removePalindromeSub("aaa") == 1
assert sol.removePalindromeSub("abab") == 2
assert sol.removePalindromeSub("abbba") == 1
assert sol.removePalindromeSub("abaab") == 2
assert sol.removePalindromeSub("abba") == 1
assert sol.removePalindromeSub("abcba") == 1
assert sol.removePalindromeSub("abcb") == 2
assert sol.removePalindromeSub("aabb") == 2
assert sol.removePalindromeSub("bbbb") == 1
assert sol.removePalindromeSub("ababab") == 2
