"""
URL: https://leetcode.com/problems/find-the-key-of-the-numbers/description/?envType=problem-list-v2&envId=vn57k9wr

3270. Find the Key of the Numbers

You are given three positive integers num1, num2, and num3.

The key of num1, num2, and num3 is defined as a four-digit number such that:

- Initially, if any number has less than four digits, it is padded with leading zeros.

- The i-th digit (1 <= i <= 4) of the key is generated by taking the smallest digit among the i-th digits of num1, num2, and num3.

Return the key of the three numbers without leading zeros (if any).


Example 1:

Input: num1 = 1, num2 = 10, num3 = 1000
Output: 0
Explanation:
On padding, num1 becomes "0001", num2 becomes "0010", and num3 remains "1000".
- The 1st digit of the key is min(0, 0, 1).
- The 2nd digit of the key is min(0, 0, 0).
- The 3rd digit of the key is min(0, 1, 0).
- The 4th digit of the key is min(1, 0, 0).
Hence, the key is "0000", i.e. 0.

Example 2:

Input: num1 = 987, num2 = 879, num3 = 798
Output: 777

Example 3:

Input: num1 = 1, num2 = 2, num3 = 3
Output: 1


Constraints:

    1 <= num1, num2, num3 <= 9999
"""


class Solution:
    def generateKey(self, num1: int, num2: int, num3: int) -> int:
        res = 0
        rem = lambda x: x % 10 if num1 else maxsize
        nums = []
        while num1 or num2 or num3:
            m = min([rem(num1), rem(num2), rem(num3)])
            nums.append((m if m != maxsize else 0))
            num1 //= 10
            num2 //= 10
            num3 //= 10
        for n in reversed(nums):
            res = res * 10 + n
        return res


sol = Solution()
assert sol.generateKey(1, 10, 1000) == 0
assert sol.generateKey(987, 879, 798) == 777
assert sol.generateKey(1, 2, 3) == 1
assert sol.generateKey(1, 1, 1) == 1
assert sol.generateKey(9999, 9999, 9999) == 9999
assert sol.generateKey(1, 10, 100) == 0
assert sol.generateKey(10, 20, 30) == 10
assert sol.generateKey(100, 200, 300) == 100
assert sol.generateKey(1000, 2000, 3000) == 1000
assert sol.generateKey(1234, 5678, 9012) == 1012
assert sol.generateKey(2, 3, 4) == 2
assert sol.generateKey(9999, 1, 5000) == 0
assert sol.generateKey(9, 9, 9) == 9
assert sol.generateKey(99, 99, 99) == 99
assert sol.generateKey(999, 999, 999) == 999
assert sol.generateKey(512, 612, 712) == 512
