"""
URL: https://leetcode.com/problems/find-the-difference/description/?envType=problem-list-v2&envId=vn57k9wr

389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.


Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.
"""


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        a = reduce(ixor, [ord(x) for x in s] or [0])
        b = reduce(ixor, [ord(x) for x in t] or [0])
        return chr(xor(a, b))


sol = Solution()

# print(sol.findTheDifference("abcd", "abcde"))  # "e"

assert sol.findTheDifference("abcd", "abcde") == "e"
assert sol.findTheDifference("", "y") == "y"
assert sol.findTheDifference("a", "aa") == "a"
assert sol.findTheDifference("abcd", "eabcd") == "e"
assert sol.findTheDifference("abcd", "abecd") == "e"
assert sol.findTheDifference("aaaa", "aaaaa") == "a"
assert sol.findTheDifference("aabbcc", "aabbccd") == "d"
assert sol.findTheDifference("xyz", "xyzz") == "z"
assert sol.findTheDifference("xyz", "zyxx") == "x"
assert sol.findTheDifference("", "a") == "a"
assert sol.findTheDifference("", "z") == "z"
assert sol.findTheDifference("a" * 1000, "a" * 1001) == "a"
assert sol.findTheDifference("a" * 1000, "a" * 1000 + "b") == "b"
assert sol.findTheDifference("ab", "bac") == "c"
assert sol.findTheDifference("hello", "ehlloo") == "o"